version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
        - "27017:27017"
    volumes:
        - mongo_data:/data/db

  basket_redis:
    container_name: basket_redis
    restart: always
    ports:
        - "6379:6379"
    volumes:
        - basket_redis:/data

  catalog.api:
    container_name: catalog.api
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - "DatabaseSetting:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
        - catalogdb
    ports:
        - "8000:80"

  basket.api:
    container_name: basket.api
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - "DatabaseSetting:ConnectionString=mongodb://basket_redis:27017"
    depends_on:
        - basket_redis
    ports:
        - "8001:80"
