version: '3.4'

services:

  portainer:
    image: portainer/portainer-ce

  catalogdb:
    image: mongo
  basketdb:
    image: redis:alpine

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile
  basket.api:
    image: ${DOCKER_REGISTRY-}basket
    build:
      context: .
      dockerfile: Basket.API/Dockerfile
volumes:
  mongo_data:
  basketdb:
  portainer:
